### ISSUE TITLE
Value of 'false' in the middle of message breaks packing

### ISSUE THREAD

**Issue by s-ol** [davidgranstrom/losc#27]
The error is here: https://github.com/davidgranstrom/losc/blob/main/src/losc/message.lua#L206

if `item` is `false` the `index` doesn't advance and so the message becomes malformed. E.g:

`losc.new_message { address = '/', types='iFi', 1, false 2 }`

**Comment by davidgranstrom** [comment]
Thanks for the report! Fixed in #28, will merge once CI passes.

I'll do a bugfix release very soon, but until then the version on develop should handle this.
