### ISSUE TITLE
1.0 release checklist

### ISSUE THREAD

**Issue by davidgranstrom** [davidgranstrom/losc#4]
- [x] Docs
- [x] Tag release
- [x] Publish on luarocks

**Comment by s-ol** [comment]
Looks like you finished the last point already ;)

Thanks for this library, the other ones on luarocks have been giving me trouble across the various target platforms for a while, I'll be very happy to switch to this soon!

**Comment by davidgranstrom** [comment]
Hi, thanks for your interest in this project!

Yes, I'm new to `luarocks` so I pushed the development version just to try it out in preparation for the 1.0 release (which should happen very soon) :) 

Please let me know if you have any thoughts or experience any issues if you decide to give this library a try!

**Comment by davidgranstrom** [comment]
`losc` v1.0.0 is now available on `luarocks`
